### ISSUE TITLE
Add #error when compiling for FW version < 0.6.0

### ISSUE THREAD

**Issue by ScruffR** [barakwei/ParticlePapertrail#1]
If you want to publish this lib on Build, you might need to change your include statement in `papertrail.cpp` from
```cpp
#include "papertrail/papertrail.h"
```
to this
```cpp
#include "papertrail.h"
```
inside the samples the first version is correct. 

For (soon to be released) Libraries 2.0 that confusion will be sorted ;-)

And to prevent confusion you might want to add a note in the sample code comment section and some explicit compile time warning `#if (SYSTEM_VERSION < 0x00060000)`, since log handlers are only available from 0.6.0 onwards.

**Comment by barakwei** [comment]
Thanks for your feedback!
The library is published on build and it seems to be working, what am I missing?
I'll add a `#error` in the header file in case FW version is too low.

**Comment by ScruffR** [comment]
I can't see it on Build. Have you published it, or have you still got the private flag next to the library name?

**Comment by barakwei** [comment]
Looks like the eye is open, should be OK, right?
![image](https://cloud.githubusercontent.com/assets/5232161/21455336/262192ce-c928-11e6-8fda-0d59c31a1408.png)

**Comment by ScruffR** [comment]
Very odd, I've cleared my cache, refreshed libraries and used incognito mode but can't find it.
Can you post a link to the library in build?

**Comment by barakwei** [comment]
Try this
https://build.particle.io/libs/585c5e64edfd74acf7000e7a/

**Comment by ScruffR** [comment]
Thanks, that helped and yes, it does build as is - so disregard what I said about the `papertrail.cpp`.
I was sure this would not have worked (in the past :blush:)

Anyway nice job :+1:

**Comment by barakwei** [comment]
It's still weird that you don't see the library in the list. I actually can't see it now, but sometimes I see "My libraries" category with the library.

**Comment by barakwei** [comment]
This is fixed in 0.0.2
