### ISSUE TITLE
Hang using electron w/ 0.6.1 

### ISSUE THREAD

**Issue by hgoldwire** [barakwei/ParticlePapertrail#7]
Hi gang,

This looks very promising, but it's hanging under 0.6.1 on an electron -- both when I include the lib in my project, and when I try the example in github.  Should this combo work?

Thanks,
Henry

**Comment by barakwei** [comment]
Unfortunately I don't have an electron (it's on its way) so I didn't try this with 0.6.1 and electron. You might have to add the source and debug a bit using serial.

**Comment by csoulakian** [comment]
Did you test it with the electron at all? It says in the readme that it works with the electron and the min firmware is 0.6.1 so I would assume that it would work. It hangs for me, too.

**Comment by barakwei** [comment]
Previous version were tested by @monkbroc on the electron. 
If you just want to make it work, you can try older versions like 0.0.2.
Mail is pretty slow here, so I'm guessing I'll get my electron in a month or so, but until then I hope someone from the community will give a shot at debugging this.

**Comment by technobly** [comment]
Hello Friends! Firmware 0.8.0-rc.3 Pre-release is out on the Web IDE for Core/Photon/P1/Electron.  This release fixes the issue seen above where recursive logging would lock up the application thread on the Electron.  It's still not advisable to log too much over UDP on the Electron.  I'll suggest two that work well below. Please see the release notes on the [Particle Firmware Updates Thread](https://community.particle.io/t/particle-firmware-updates-thread/14378/60)

```cpp
// app level over papertrail
PapertrailLogHandler papertrailLogHandler1(PAPERTRAIL_HOSTNAME, PAPERTRAIL_PORT, "MyAppName", System.deviceID(),
    LOG_LEVEL_NONE, {
    { "app", LOG_LEVEL_ALL }
    // TOO MUCH!!! { "system", LOG_LEVEL_ALL },
    // TOO MUCH!!! { "comm", LOG_LEVEL_ALL }
});

// system info and app level over papertrail
PapertrailLogHandler papertrailLogHandler2(PAPERTRAIL_HOSTNAME, PAPERTRAIL_PORT, "MyAppName", System.deviceID(),
    LOG_LEVEL_NONE, {
    { "app", LOG_LEVEL_ALL },
    { "system", LOG_LEVEL_INFO }
    // MAYBE { "comm", LOG_LEVEL_INFO }
});
```
